### ISSUE TITLE
Comunicação por meio de RSU e disseminação por meio de inundação

### ISSUE THREAD

**Issue by TAlfaCentauro** [dnatividade/Vanet-Projects#37]
Tenho um cenário de uma rede VANET com várias RSUs. Preciso que determinados veículos possam se comunicar com outros veículos, localizados em diferentes posições no cenário, por meio da RSU. Caso o veículo de destino esteja muito distante, use flooding para que, eventualmente, o veículo de destino receba a mensagem enviada.
Ficarei muito grato por sua ajuda valiosa.

**Comment by dnatividade** [comment]
Olá.
Consegue me mandar seu projeto pra eu testar e ver o que já conseguiu fazer?

**Comment by TAlfaCentauro** [comment]
Obrigado por sua resposta.
Já o convidei para colaborar com meu repositório “Project-VANET”. Estou usando seu projeto como base: [01 Simple Projects/007 CAR send msg to another car via RSU] (https://github.com/dnatividade/Vanet-Projects/tree/d2d221a9681cffae6ca1b3da8a56ad15f9d8599a/01%20Simple%20Projects/007%20CAR%20send%20msg%20to%20another%20car%20via%20RSU)

**Comment by dnatividade** [comment]
Agradeço pelo convite, mas acredito que não vou conseguir ajudá-lo em seu projeto colaborativo, pois faz mais de 3 anos que não trabalho mais com redes veiculares e seus simuladores.

Eu costumo reservar algumas poucas horas da minha semana para responder algumas perguntas ou dar algumas dicas. Só!

Mas de qualquer forma, acabei de aceitar seu convite e talvez eu seja útil em algo.
